name: Setup repo
description: Installs node and pnpm and then the dependencies.

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      id: pnpm-setup
      uses: pnpm/action-setup@v2
      with:
        version: 7.18.2
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
